name: NuGet Release

on:
  push:
    branches: [ main ] # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      awsaccesskeyid: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      awssecretaccesskey: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}    
    with:
      slnfilename: Digitalroot.Valheim.Common.References
      projfilename: Digitalroot.Valheim.Common.References
      #srcpath: src
      #unittestpath: UnitTests
      skipunittest: true
      forceassemblyversion: true
      #awsregion: us-west-2
      #create-github-release: false
      #aws-region: us-west-2
      nuget-gh-upload: true
      nuget-s3-upload: true
      #nexus-enable-upload: true
      #nexus-mod-id: 000
