name: Release

on:
  push:
    branches: [ main ] # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
    with:
      sln-file-name: Digitalroot.Valheim.Common.References
      proj-file-name: Digitalroot.Valheim.Common.References
      #src-path: src
      #unit-test-path: UnitTests
      skip-unit-tests: true
      force-assembly-version: true
      #awsregion: us-west-2
      #create-github-release: false
      #aws-region: us-west-2
      nuget-gh-upload: true
      nuget-s3-upload: true
